<?php

/**
 * @file
 * Integrates Recline.js visualization tools.
 */

/**
 * Implements hook_theme().
 */
function dkan_datastore_recline_theme() {
  return array(
    'dkan_datastore_recline_default_formatter' => array(
      'variables' => array('item' => NULL),
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function dkan_datastore_recline_field_formatter_info() {
  $formatters = array(
    'dkan_datastore_recline_default_formatter' => array(
      'label' => t('DKAN Recline.js'),
      'field types' => array('recline_field', 'file'),
      // TODO: add some settings.
      'settings' => array(),
    ),
  );
  return $formatters;
}

/**
 * Implements hook_field_formatter_view().
 */
function dkan_datastore_recline_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  foreach ($items as $delta => $item) {
    $item['entity'] = $entity;
    $element[$delta] = array(
      '#theme' => 'dkan_datastore_recline_default_formatter',
      '#item' => $item,
    );
  }

  return $element;
}

/**
 * Returns HTML for an recline field formatter.
 *
 * @param array $variables
 *   An associative array containing:
 *   - item: Associative array of recline field
 *
 * @ingroup themeable
 */
function theme_dkan_datastore_recline_default_formatter($variables) {
  $file = $variables['item'];

  $url = file_create_url($file['uri']);

  $icon = '';

  // Set options as per anchor format described at
  // http://microformats.org/wiki/file-format-examples
  $options = array(
    'attributes' => array(
      'type' => $file['filemime'] . '; length=' . $file['filesize'],
    ),
  );

  // Use the description as the link text if available.
  if (empty($file['description'])) {
    $link_text = $file['filename'];
  }
  else {
    $link_text = $file->description;
    $options['attributes']['title'] = check_plain($file['filename']);
  }
  $dkan = module_exists('dkan_datastore') ? TRUE : FALSE;
  if (isset($variables['item']['grid'])) {
    if ($variables['item']['grid'] || $variables['item']['graph'] || $variables['item']['map']) {
      $uuid = $variables['item']['entity']->uuid;
      drupal_add_library('system', 'ui.sortable');
      $recline = libraries_load('recline');
      $module_path = drupal_get_path('module', 'dkan_datastore_recline');
      drupal_add_js($module_path . '/recline.app.js');
      drupal_add_css($module_path . '/recline.css');
      $file_path = file_create_url($variables['item']['uri']);
      $settings['recline'] = array(
        'file' => $file_path,
        'grid' => (int) $variables['item']['grid'],
        'graph' => (int) $variables['item']['graph'],
        'map' => (int) $variables['item']['map'],
        'uuid' => $uuid,
        'fileType' => $variables['item']['filemime'],
        'dkan' => $dkan,
      );
      drupal_add_js($settings, 'setting');
    }
  }
  else {
    $uuid = $variables['item']['entity']->uuid;
    drupal_add_library('system', 'ui.sortable');
    $recline = libraries_load('recline');
    $module_path = drupal_get_path('module', 'dkan_datastore_recline');
    drupal_add_js($module_path . '/recline.app.js');
    drupal_add_css($module_path . '/recline.css');
    $file_path = file_create_url($variables['item']['uri']);
    $settings['recline'] = array(
      'file' => $file_path,
      'uuid' => $uuid,
      'grid' => 1,
      'graph' => 1,
      'map' => 1,
      'fileType' => $variables['item']['filemime'],
      'dkan' => $dkan,
    );
    drupal_add_js($settings, 'setting');
  }

  $file = l('Download', $url, $options);
  return '<div class="download">' . $file . '</div><span class="data-explorer"></span>';
}
