<?php
define('DKAN_DATASTORE_BATCH_IMPORT', 0);
define('DKAN_DATASTORE_FAST_IMPORT', 1);
define('DKAN_DATASTORE_DYNAMIC_IMPORT', 2);

/**
 * Implements hook_menu().
 */
function dkan_datastore_fast_import_menu() {
  $items['admin/dkan/datastore'] = array(
    'title' => 'DKAN Datastore',
    'description' => 'Settings for DKAN Datastore.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dkan_datastore_fast_import_settings'),
    'access arguments' => array('manage datastore settings')
  );

  return $items;
}

function dkan_datastore_fast_import_settings(){
  $form = array();

  $options = array(
    DKAN_DATASTORE_BATCH_IMPORT => t('Use regular import as default (BATCH)'),
    DKAN_DATASTORE_FAST_IMPORT => t('Use fast import as default (LOAD DATA)'),
    DKAN_DATASTORE_DYNAMIC_IMPORT => t('Use fast import for files with a weight over:'),
  );

  $form['dkan_datastore_fast_import_selection'] = array(
    '#type' => 'radios',
    '#title' => t('Fast Import Selection'),
    '#options' => $options,
    '#default_value' => variable_get('dkan_datastore_fast_import_selection', 0),
  );

  $form['dkan_datastore_fast_import_selection_threshold'] = array(
    '#type' => 'textfield',
    '#title' => t('File size threshold'),
    '#size' => 50,
    '#default_value' => variable_get('dkan_datastore_fast_import_selection_threshold', DkanDatastoreFastImport::FAST_IMPORT_THRESHOLD_DEFAULT),
    '#description' => '',
    '#states' => array(
      'visible' => array(
        ':input[name="dkan_datastore_fast_import_selection"]' => array('value' => DKAN_DATASTORE_DYNAMIC_IMPORT),
      ),
    )
  );

  $options = array(
    'load_data_local_infile' => t('LOAD DATA LOCAL INFILE'),
    'load_data_infile' => t('LOAD DATA INFILE'),
  );
  $form['dkan_datastore_load_data_type'] = array(
    '#type' => 'radios',
    '#title' => t('Load Data Statement'),
    '#options' => $options,
    '#description' => t('Choose the version of load data you want to use. This depends on your hosting configuration.'),
    '#default_value' => variable_get('dkan_datastore_load_data_type', 'load_data_local_infile'),
    '#states' => array(
      'invisible' => array(
        ':input[name="dkan_datastore_fast_import_selection"]' => array('value' => DKAN_DATASTORE_BATCH_IMPORT),
      ),
    )
  );

  $form['queue_filesize_threshold'] = array(
    '#type' => 'textfield',
    '#title' => t('Queue Filesize Threshold'),
    '#size' => 50,
    '#default_value' => variable_get('queue_filesize_threshold', DkanDatastoreFastImport::QUEUE_FILESIZE_THRESHOLD_DEFAULT),
    '#description' => 'Above this number all the imports will be queued. Make sure you have the a command line cron to run these imports.',
    '#states' => array(
      'invisible' => array(
        ':input[name="dkan_datastore_fast_import_selection"]' => array('value' => DKAN_DATASTORE_BATCH_IMPORT),
      ),
    )
  );
  $form['#submit'][] = 'dkan_datastore_fast_import_settings_submit';

  return system_settings_form($form);
}

function dkan_datastore_fast_import_settings_submit($form, &$form_state) {
  $fast_import_selection = $form_state['values']['dkan_datastore_fast_import_selection'];
  $class = ($fast_import_selection != DKAN_DATASTORE_BATCH_IMPORT) ? 'DkanDatastoreFastImport' : 'DkanDatastore';
  variable_set('dkan_datastore_class', $class);
}

/**
 * Get the datastore queue name.
 */
function dkan_datastore_fast_import_queue_name() {
  return 'dkan_datastore_fast_import_queue';
}

/**
 * Implements hook_cron_queue_info().
 */
function dkan_datastore_fast_import_cron_queue_info() {
  return array(
    dkan_datastore_fast_import_queue_name() => array(
      'worker callback' => 'dkan_datastore_fast_import_import_queue_worker',
      'skip on cron' => TRUE,
      'time' => 600,
    ),
  );
}

/**
 * Import csv using the most performant way.
 */
function dkan_datastore_fast_import_import($source, $node, $table, $config){
  $load_data_type = variable_get('dkan_datastore_load_data_type', 'load_data_local_infile');
  $file = $node->field_upload->value();
  $file_path = drupal_realpath($file->uri);
  $feeds_entity_id = $source->feed_nid;
  $fields = implode(',', array_keys($table->meta['fields']));
  $delim = $config['delimiter'];
  $has_headers = ($config['no_headers']) ? '' : 'IGNORE 1 LINES';

  $load_data_statement = ($load_data_type === 'load_data_local_infile') ? 'LOAD DATA LOCAL' : 'LOAD DATA';

  $sql = $load_data_statement . " INFILE '$file_path' IGNORE
   INTO TABLE $table->name
   COLUMNS TERMINATED BY '$delim' LINES TERMINATED BY '\n' $has_headers ($fields)
   SET timestamp=UNIX_TIMESTAMP(), feeds_entity_id=$feeds_entity_id;";

  db_query($sql);
  $node->field_datastore_status->set(DKAN_DATASTORE_EXISTS);
  $node->save();
}

function dkan_datastore_fast_import_import_queue_worker($item){
  dkan_datastore_fast_import_import($item['source'], $item['node'], $item['table'], $item['config']);
}

/**
 * Implements hook_form_alter().
 */
function dkan_datastore_fast_import_form_alter(&$form, &$form_state, $form_id){
  if($form_id == 'dkan_datastore_import_tab_form'){
    $node = entity_metadata_wrapper('node', $form_state['build_info']['args'][0]);
    $file = $node->field_upload->value();
    $selection = variable_get('dkan_datastore_fast_import_selection', DKAN_DATASTORE_BATCH_IMPORT);
    $use_fast_import = FALSE;

    if($selection == DKAN_DATASTORE_DYNAMIC_IMPORT) {
      $threshold = variable_get('dkan_datastore_fast_import_selection_threshold', DkanDatastoreFastImport::FAST_IMPORT_THRESHOLD_DEFAULT);
      if($file->filesize > parse_size($threshold)) {
        $use_fast_import = TRUE;
      }
    } else if($selection == DKAN_DATASTORE_FAST_IMPORT) {
      $use_fast_import = TRUE;
    } else {
      $use_fast_import = FALSE;
    }

    $form['use_fast_import'] = array(
      '#type' => 'checkbox',
      '#title' => t('Use Fast Import'),
      '#default_value' => $use_fast_import,
      '#states' => array(
        'disabled' => array(
          ':input[name="FeedsFlatstoreProcessor[geolocate]"]' => array('checked' => TRUE),
        ),
      )
    );
    $form['#attached']['js'][] = array(
      'data' => drupal_get_path('module', 'dkan_datastore_fast_import'). '/dkan_datastore_fast_import.js',
      'type' => 'file'
    );
  }
}